export interface Course {
  id: string;
  title: string;
  category: string;
  categoryIcon: string;
  description: string;
  image: string;
  recommended?: boolean;
  duration: string;
  level: "Beginner" | "Intermediate" | "Advanced" | "All Levels";
  link: string;
  enrollLink: string;
  highlights: string[];
}

export const TRAINING_CATEGORIES = [
  "All",
  "AI & ML",
  "Python",
  "Web Development",
  "Mobile App Development",
  "Java",
  ".NET",
  "Graphics & Video Editing",
  "Digital Marketing",
  "Cybersecurity",
  "DevOps & Cloud",
  "Networking",
  "Database",
  "Data Science & Analytics",
  "QA & Testing",
  "Accounting",
  "Other Courses",
];

export const COURSES: Course[] = [
  // AI
  {
    id: "vibe-coding-claude-ai",
    title: "Vibe Coding with Claude AI",
    category: "AI & ML",
    categoryIcon: "🤖",
    description: "Learn to build full-stack applications effortlessly by pairing with Anthropic's Claude AI for rapid vibe coding and architecture.",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format",
    recommended: true,
    duration: "1.5 Months",
    level: "All Levels",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Prompting Workflows", "Agentic Systems", "100% Practical"],
  },
  {
    id: "ai-for-business-leaders",
    title: "AI for Business Leaders & Managers",
    category: "AI & ML",
    categoryIcon: "🤖",
    description: "Strategic AI adoption, executive workflow automation, ROI analysis, and enterprise AI governance.",
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&auto=format",
    recommended: false,
    duration: "1 Month",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Executive AI Strategy", "ROI & Governance", "Case Studies"],
  },
  {
    id: "agentic-ai",
    title: "Agentic AI",
    category: "AI & ML",
    categoryIcon: "🤖",
    description: "Master autonomous multi-agent frameworks, tool-use LLMs, and agentic task orchestration.",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format",
    recommended: true,
    duration: "2 Months",
    level: "Advanced",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Multi-Agent Architectures", "Tool Calling", "Autonomous Workflows"],
  },
  {
    id: "ai-for-everyone",
    title: "AI For Everyone",
    category: "AI & ML",
    categoryIcon: "🤖",
    description: "A non-technical introduction to artificial intelligence, machine learning principles, and daily AI tools.",
    image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&auto=format",
    recommended: false,
    duration: "3 Weeks",
    level: "Beginner",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["No-Code Introduction", "Productivity Tools", "Generative AI"],
  },
  {
    id: "prompt-engineering",
    title: "Prompt Engineering",
    category: "AI & ML",
    categoryIcon: "🤖",
    description: "Master system prompting, chain-of-thought, RAG context construction, and LLM optimization techniques.",
    image: "https://images.unsplash.com/photo-1686191567764-146560961be3?w=800&auto=format",
    recommended: true,
    duration: "1 Month",
    level: "All Levels",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["System Prompts", "RAG Integration", "Model Tuning"],
  },
  {
    id: "ai-with-python-llms",
    title: "AI with Python: Machine Learning, Deep Learning & Generative AI (LLMs)",
    category: "AI & ML",
    categoryIcon: "🤖",
    description: "End-to-end Python AI track covering PyTorch, Scikit-Learn, Transformers, Fine-Tuning LLMs, and RAG.",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format",
    recommended: true,
    duration: "3.5 Months",
    level: "Advanced",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["PyTorch & Transformers", "LLM Fine-Tuning", "Project Portfolio"],
  },

  // Python
  {
    id: "python-django-training",
    title: "Python & Django Training",
    category: "Python",
    categoryIcon: "🐍",
    description: "Master Python fundamentals, object-oriented programming, and build robust web backends with Django & REST API.",
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&auto=format",
    recommended: true,
    duration: "2.5 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Django REST Framework", "PostgreSQL Integration", "Live Capstone Project"],
  },
  {
    id: "data-science-ml-genai",
    title: "Data Science & ML with GenAI",
    category: "Python",
    categoryIcon: "🐍",
    description: "Analyze datasets, build predictive ML models, and integrate generative AI capabilities into data pipelines.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format",
    recommended: true,
    duration: "3 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Pandas & Scikit-Learn", "GenAI Data Pipelines", "Certification Included"],
  },
  {
    id: "advanced-data-analysis-python",
    title: "Advanced Data Analysis with Python",
    category: "Python",
    categoryIcon: "🐍",
    description: "Deep dive into Pandas, NumPy, Seaborn, exploratory data analysis, statistical modeling, and automated reporting.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format",
    recommended: false,
    duration: "2 Months",
    level: "Advanced",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Exploratory Data Analysis", "Statistical Modeling", "Interactive Dashboards"],
  },

  // Web Development
  {
    id: "web-design-training",
    title: "Web Design Training",
    category: "Web Development",
    categoryIcon: "🌐",
    description: "Learn modern UI principles, responsive layout design, HTML5, CSS3, and interactive frontend creation.",
    image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format",
    recommended: false,
    duration: "2 Months",
    level: "Beginner",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Responsive UI/UX", "CSS Grid & Flexbox", "Portfolio Website"],
  },
  {
    id: "html-css-javascript",
    title: "HTML, CSS & JavaScript",
    category: "Web Development",
    categoryIcon: "🌐",
    description: "The essential building blocks of web development. Build dynamic, interactive websites from scratch.",
    image: "https://images.unsplash.com/photo-1593720213428-28a5b9e94613?w=800&auto=format",
    recommended: false,
    duration: "1.5 Months",
    level: "Beginner",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["ES6+ JavaScript", "DOM Manipulation", "Hands-on Labs"],
  },
  {
    id: "bootstrap-training",
    title: "Bootstrap Training",
    category: "Web Development",
    categoryIcon: "🌐",
    description: "Rapidly build mobile-first responsive web pages using Bootstrap grid system and UI components.",
    image: "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=800&auto=format",
    recommended: false,
    duration: "1 Month",
    level: "Beginner",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Grid Layouts", "Custom Themes", "Fast Prototyping"],
  },
  {
    id: "php-laravel",
    title: "PHP with Laravel",
    category: "Web Development",
    categoryIcon: "🌐",
    description: "Build secure, scalable backend applications using PHP 8 and the popular Laravel framework.",
    image: "https://images.unsplash.com/photo-1599507593499-a3f7d7d97667?w=800&auto=format",
    recommended: false,
    duration: "2.5 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Laravel Eloquent ORM", "Blade Templating", "REST API Development"],
  },
  {
    id: "react-js-training",
    title: "React JS Training",
    category: "Web Development",
    categoryIcon: "🌐",
    description: "Component architecture, React Hooks, Redux Toolkit, React Router, and modern SPA frontend development.",
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&auto=format",
    recommended: true,
    duration: "2 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["React Hooks & Context", "Redux Toolkit", "API Integration"],
  },
  {
    id: "nextjs-training",
    title: "Next.js Training",
    category: "Web Development",
    categoryIcon: "🌐",
    description: "Full-stack React with Next.js App Router, Server Components (RSC), SSR, Edge API routes, and Tailwind CSS.",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format",
    recommended: true,
    duration: "2 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Next.js 16 App Router", "Server Actions & RSC", "SEO Optimization"],
  },
  {
    id: "nodejs-training",
    title: "Node.js Training",
    category: "Web Development",
    categoryIcon: "🌐",
    description: "Asynchronous JavaScript runtime, Express.js microservices, RESTful APIs, WebSockets, and database connectivity.",
    image: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800&auto=format",
    recommended: false,
    duration: "2 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Express.js Microservices", "JWT Authentication", "MongoDB Integration"],
  },
  {
    id: "mern-stack-development",
    title: "MERN Stack Development",
    category: "Web Development",
    categoryIcon: "🌐",
    description: "Complete full-stack JavaScript mastery: MongoDB, Express.js, React.js, and Node.js with real enterprise projects.",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format",
    recommended: true,
    duration: "3 Months",
    level: "All Levels",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Full-Stack JavaScript", "Real-World Projects", "Career Support"],
  },
  {
    id: "mean-stack-development",
    title: "MEAN Stack Development",
    category: "Web Development",
    categoryIcon: "🌐",
    description: "Enterprise full-stack JavaScript with MongoDB, Express.js, Angular, and Node.js.",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format",
    recommended: false,
    duration: "3 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Angular Framework", "Enterprise Architecture", "RESTful APIs"],
  },
  {
    id: "python-django-fullstack",
    title: "Python Django Full Stack",
    category: "Web Development",
    categoryIcon: "🌐",
    description: "Combine HTML/CSS/JS frontend with Django backend, PostgreSQL database, and cloud deployment.",
    image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&auto=format",
    recommended: true,
    duration: "3 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["End-to-End Development", "Database Optimization", "AWS Deployment"],
  },

  // Mobile App Development
  {
    id: "flutter-training",
    title: "Flutter Training",
    category: "Mobile App Development",
    categoryIcon: "📱",
    description: "Cross-platform mobile app development with Dart, Flutter widgets, state management (Bloc/Provider), and Firebase.",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&auto=format",
    recommended: false,
    duration: "2.5 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Dart Language", "Bloc State Management", "Firebase Backend"],
  },
  {
    id: "android-training",
    title: "Android Training",
    category: "Mobile App Development",
    categoryIcon: "📱",
    description: "Native Android development with Kotlin, Jetpack Compose, Room database, and Google Play publication.",
    image: "https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=800&auto=format",
    recommended: false,
    duration: "2.5 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Kotlin & Jetpack Compose", "Room Database", "Play Store Publishing"],
  },
  {
    id: "react-native-training",
    title: "React Native Training",
    category: "Mobile App Development",
    categoryIcon: "📱",
    description: "Build native iOS and Android apps using React and JavaScript/TypeScript with shared codebase efficiency.",
    image: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&auto=format",
    recommended: true,
    duration: "2.5 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Cross-Platform Mobile", "Native Modules", "Performance Tuning"],
  },
  {
    id: "ios-development",
    title: "iOS Development",
    category: "Mobile App Development",
    categoryIcon: "📱",
    description: "Native iOS app development using Swift, SwiftUI, CoreData, and Apple App Store deployment guidelines.",
    image: "https://images.unsplash.com/photo-1563206767-5b18f218e8de?w=800&auto=format",
    recommended: false,
    duration: "2.5 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["SwiftUI & Xcode", "CoreData Persistence", "App Store Guidelines"],
  },

  // Java
  {
    id: "core-java",
    title: "Core Java",
    category: "Java",
    categoryIcon: "☕",
    description: "Object-oriented programming, data structures, multithreading, collections framework, and exception handling.",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format",
    recommended: false,
    duration: "2 Months",
    level: "Beginner",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["OOP Concepts", "Collections Framework", "Multithreading"],
  },
  {
    id: "advanced-java",
    title: "Advanced Java",
    category: "Java",
    categoryIcon: "☕",
    description: "Servlets, JSP, JDBC, Hibernate ORM, and enterprise Java application architecture.",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format",
    recommended: false,
    duration: "2 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Hibernate ORM", "Servlets & JSP", "Database Connectivity"],
  },
  {
    id: "spring-boot",
    title: "Spring Boot",
    category: "Java",
    categoryIcon: "☕",
    description: "Build cloud-native Java microservices with Spring Boot, Spring Data JPA, Spring Security, and REST APIs.",
    image: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=800&auto=format",
    recommended: false,
    duration: "2 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Spring Cloud Microservices", "Spring Security", "JWT Authentication"],
  },
  {
    id: "java-full-stack",
    title: "Java Full Stack",
    category: "Java",
    categoryIcon: "☕",
    description: "Full-stack enterprise development combining Angular/React with Spring Boot and PostgreSQL/MySQL backend.",
    image: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format",
    recommended: false,
    duration: "3.5 Months",
    level: "All Levels",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Enterprise Full-Stack", "Spring Boot + React", "Production Deployment"],
  },

  // .NET
  {
    id: "csharp-training",
    title: "C# Training",
    category: ".NET",
    categoryIcon: "🔷",
    description: "Learn fundamental C# programming, .NET runtime, LINQ, async programming, and OOP concepts.",
    image: "https://images.unsplash.com/photo-1580927752452-89d86da3fa0a?w=800&auto=format",
    recommended: false,
    duration: "1.5 Months",
    level: "Beginner",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["C# Language Essentials", "LINQ Queries", "Async/Await"],
  },
  {
    id: "aspnet-mvc",
    title: "ASP.NET MVC",
    category: ".NET",
    categoryIcon: "🔷",
    description: "Build robust web applications using ASP.NET Model-View-Controller architecture and Entity Framework.",
    image: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&auto=format",
    recommended: false,
    duration: "2 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["MVC Architecture", "Entity Framework", "SQL Server Integration"],
  },
  {
    id: "aspnet-core",
    title: "ASP.NET Core",
    category: ".NET",
    categoryIcon: "🔷",
    description: "Cross-platform enterprise web development with .NET Core, Web APIs, Dependency Injection, and EF Core.",
    image: "https://images.unsplash.com/photo-1516116211223-48a12725dd24?w=800&auto=format",
    recommended: false,
    duration: "2.5 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Cross-Platform .NET", "RESTful Web APIs", "Dependency Injection"],
  },
  {
    id: "dotnet-full-stack",
    title: "NET Full Stack",
    category: ".NET",
    categoryIcon: "🔷",
    description: "End-to-end Microsoft stack development combining React/Angular with ASP.NET Core Web API and SQL Server.",
    image: "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=800&auto=format",
    recommended: false,
    duration: "3.5 Months",
    level: "All Levels",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Full Microsoft Stack", "React + ASP.NET Core", "Azure Cloud Hosting"],
  },

  // Graphics & Video Editing
  {
    id: "graphic-design",
    title: "Graphic Design",
    category: "Graphics & Video Editing",
    categoryIcon: "🎨",
    description: "Design theory, brand identity creation, typography, color systems, and visual communication.",
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format",
    recommended: false,
    duration: "2.5 Months",
    level: "Beginner",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Photoshop & Illustrator", "Brand Identity", "Print & Digital Media"],
  },
  {
    id: "ui-ux-design-figma",
    title: "UI/UX Design with Figma",
    category: "Graphics & Video Editing",
    categoryIcon: "🎨",
    description: "User research, wireframing, high-fidelity UI design, component libraries, and interactive prototyping in Figma.",
    image: "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=800&auto=format",
    recommended: true,
    duration: "2 Months",
    level: "All Levels",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Figma Prototyping", "User Research & Flow", "Design Systems"],
  },
  {
    id: "video-editing-premiere-pro",
    title: "Video Editing with Premiere Pro & After Effects",
    category: "Graphics & Video Editing",
    categoryIcon: "🎨",
    description: "Timeline editing, color grading, audio mixing, visual effects, and motion graphics creation.",
    image: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&auto=format",
    recommended: false,
    duration: "2.5 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Adobe Premiere Pro", "After Effects VFX", "Motion Graphics"],
  },

  // Digital Marketing
  {
    id: "digital-marketing-360-ai",
    title: "Digital Marketing 360° with AI",
    category: "Digital Marketing",
    categoryIcon: "📈",
    description: "Comprehensive digital marketing mastering SEO, Social Media Ads, Content Strategy, Google Analytics, and AI tools.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format",
    recommended: false,
    duration: "2.5 Months",
    level: "All Levels",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["SEO & Google Ads", "Social Media Campaigning", "AI Marketing Automation"],
  },
  {
    id: "seo-training",
    title: "SEO Training",
    category: "Digital Marketing",
    categoryIcon: "📈",
    description: "On-page, off-page, technical SEO, keyword research, link building strategies, and Google Search Console optimization.",
    image: "https://images.unsplash.com/photo-1571721795195-a2ca2d3370a9?w=800&auto=format",
    recommended: false,
    duration: "1.5 Months",
    level: "Beginner",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["On-Page & Technical SEO", "Keyword Research", "Rank Optimization"],
  },

  // Cybersecurity
  {
    id: "ethical-hacking-cybersecurity",
    title: "Ethical Hacking & Cybersecurity Training",
    category: "Cybersecurity",
    categoryIcon: "🔐",
    description: "Network vulnerability auditing, penetration testing tools (Kali Linux, Wireshark, Metasploit), and CEH exam prep.",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format",
    recommended: false,
    duration: "2.5 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Kali Linux & Tools", "Penetration Testing", "CEH Exam Preparation"],
  },

  // DevOps & Cloud
  {
    id: "devops-training",
    title: "DevOps Training",
    category: "DevOps & Cloud",
    categoryIcon: "🌩️",
    description: "CI/CD pipelines, Docker containerization, Kubernetes orchestration, Infrastructure as Code (Terraform), and GitOps.",
    image: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&auto=format",
    recommended: true,
    duration: "3 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Docker & Kubernetes", "Jenkins CI/CD", "Terraform Infrastructure"],
  },
  {
    id: "aws-solution-architect",
    title: "AWS Solution Architect",
    category: "DevOps & Cloud",
    categoryIcon: "🌩️",
    description: "Architect cloud infrastructure on Amazon Web Services: EC2, S3, RDS, Lambda, VPC, IAM, and high availability systems.",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format",
    recommended: true,
    duration: "2.5 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["AWS Core Services", "High Availability & VPC", "AWS Certification Prep"],
  },

  // Networking
  {
    id: "ccna-cisco-networking",
    title: "CCNA (Cisco Certified Network Associate)",
    category: "Networking",
    categoryIcon: "🌐",
    description: "Network fundamentals, IP routing, switching, wireless setup, security fundamentals, and automation concepts.",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format",
    recommended: false,
    duration: "2.5 Months",
    level: "Beginner",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Cisco Routing & Switching", "IP Subnetting", "CCNA Certification Prep"],
  },

  // Database
  {
    id: "sql-dba-mongodb",
    title: "Database Administration & NoSQL (SQL & MongoDB)",
    category: "Database",
    categoryIcon: "🗄️",
    description: "Relational database design, complex SQL queries, index tuning, backup strategies, and MongoDB document database.",
    image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&auto=format",
    recommended: false,
    duration: "2 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Complex Queries & Tuning", "DBA Backup & Security", "MongoDB NoSQL"],
  },

  // Data Science & Analytics
  {
    id: "power-bi-analytics",
    title: "Power BI",
    category: "Data Science & Analytics",
    categoryIcon: "📊",
    description: "Transform raw data into interactive business dashboards, DAX expressions, data modeling, and executive reports.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format",
    recommended: true,
    duration: "1.5 Months",
    level: "Beginner",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["DAX Expressions", "Data Modeling", "Executive Dashboards"],
  },

  // QA & Testing
  {
    id: "software-testing-qa",
    title: "Software Testing (QA)",
    category: "QA & Testing",
    categoryIcon: "🧪",
    description: "Manual test case design, bug tracking, API testing with Postman, and Selenium automation with Java/Python.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format",
    recommended: true,
    duration: "2 Months",
    level: "Beginner",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Manual & Automation Testing", "Selenium Webdriver", "API Testing with Postman"],
  },

  // Accounting
  {
    id: "tally-quickbooks-accounting",
    title: "Accounting Training Package (Tally & QuickBooks)",
    category: "Accounting",
    categoryIcon: "💼",
    description: "Practical accounting principles, computerized book-keeping, VAT calculation, income tax, and financial reporting.",
    image: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format",
    recommended: false,
    duration: "1.5 Months",
    level: "Beginner",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["Tally Prime & QuickBooks", "VAT & Income Tax", "Financial Auditing"],
  },

  // Other Courses
  {
    id: "autocad-gis-erp",
    title: "AutoCAD, GIS & Specialized Technical Packages",
    category: "Other Courses",
    categoryIcon: "📋",
    description: "Professional drafting, 2D/3D CAD design, spatial data mapping with GIS, and Enterprise Resource Planning.",
    image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&auto=format",
    recommended: false,
    duration: "2 Months",
    level: "Intermediate",
    link: "https://broadwayinfosys.com/courses",
    enrollLink: "https://broadwayinfosys.com/enroll-now",
    highlights: ["AutoCAD 2D/3D", "GIS Spatial Mapping", "ERP Fundamentals"],
  },
];
